[alias]
r = "run"
h = "run --target x86_64-unknown-linux-gnu"

[build]
target = "wasm32-unknown-unknown"

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"
rustc-env = {wasm="true"}

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1
